import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar />
        <div className="my-3">{children}</div>
      </body>
    </html>
  );
}
