import getAllUsers from "@/lib/getAllUsers";
import Link from "next/link";
import React from "react";

export const metadata = {
  title: "List user",
  description: "Generated by List user",
};

export default async function UserPage(props) {
  const users = await getAllUsers();

  const content = (
    <section>
      <h2>
        <Link href="/">Back to Home</Link>
      </h2>
      <br />
      <ul>
        {users.map((user) => (
          <li key={user.id}>
            <Link href={`/users/${user.id}`}>{user.name}</Link>
          </li>
        ))}
      </ul>
    </section>
  );
  return content;
}
