import MyProfilePic from "../components/MyProfilePic";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Blog",
  description: "Generated by Blog",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar />
        <MyProfilePic />
        {children}
      </body>
    </html>
  );
}
