// import { Inter } from "next/font/google";
import Link from "next/link";
import Posts from "../components/Posts";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog",
  description: "Generated by search page",
};

export default function Blog() {
  return (
    <main className="px-6 mx-auto">
      <p className="mt-12 mb-12 text-3xl text-center dark:text-white">
        Hello and Welcome 👋&nbsp;
        <span className="whitespace-nowrap">
          I&apos;m <span className="font-bold">Tim</span>.
        </span>
      </p>
      <Posts />
    </main>
  );
}
