import "./globals.css";

export const metadata = {
  title: "Home",
  description: "Generated by Home",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">{children}</body>
    </html>
  );
}
