// import { Inter } from "next/font/google";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by home",
};

export default function Home() {
  return (
    <main>
      <h1 className="text-3xl font-bold underline">Home page</h1>
    </main>
  );
}
